### PR TITLE
configmap_source: add KubernetesConfigMap source

### PR DESCRIPTION
**Pull request by kevinburkesegment**
We can use this to load a Kubernetes ConfigMap mounted volume as
a conf.Source.

I hope to expand on this to allow people to subscribe to values so
that running programs can get notified about updated configuration
values. However this is less of a priority as the first application is
to use them from Terraform, which does not change that much.

### CODE REVIEW

**Review by achille-roussel — COMMENTED** [review]
The files in `testdata` have names starting with `..`, is that expected?

**Comment by kevinburkesegment** [comment]
> The files in testdata have names starting with .., is that expected?

Yes that's how configmap mounts them into the pod - I believe it updates values by updating the symlinks to point at different files.

**Comment by kevinburkesegment** [comment]
Achille notes:

- What if you want to watch hundreds of configs? 
- Just set the interval for people. Every 1 second or 5 seconds or 10 seconds is fine.

**Review by achille-roussel — APPROVED** [review]
The change looks good, let's try it out! 🚀

**Pull request merged**
